### ISSUE TITLE
Need help on how to use community-config

### ISSUE THREAD

**Issue by anupam312nwd** [VSpaceCode/community-configs#5]
Hi, I am a noob in using VS Code.
Can someone help how to use [vspacecode-config.json](https://github.com/VSpaceCode/community-configs/blob/master/doom/vspacecode-config.json) file?
Should I copy its content to `~/.vscode/settings.json` or `keybindings.json` or 
where to store this file and make `~/.vscode/settings.json` use it? 
I tried to look for VSpaceCode documentation but could not find it.

It will be great if this can be added to readme of community config.
Thanks!

**Comment by marcoieni** [comment]
keybindings.json 👍

> It will be great if this can be added to readme of community config.

PR welcome 👍
